[package]
name = "python_bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "python_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
reqwest = "0.11.22"
deno_core = "0.221.0"
tokio = { version = "1.32.0", features = ["full"] }
deno_ast = { version = "0.29.5", features = ["transpiling"] }

[build-dependencies]
deno_core = "0.221.0"